[application]
name = "pride_kitchen"
asset_dir = "assets"

[web.app]
title = "Pride Kitchen ğŸ´"

[web.watcher]
index_on_404 = true

[bundle]
identifier = "com.maksymshcherbak.pridemixer"
icon = ["favicon.ico"]
resources = ["*", "*/*"]
